name: Feature request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "Please describe the problem you want to solve and the impact."
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What is missing or painful today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like SOZLab to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?
